src/main/java/ca/bc/gov/splunknotificationservice/Configuration/SplunkProperites.java, src/main/java/ca/bc/gov/splunknotificationservice/Controller/AlertNotificationController.java, src/main/java/ca/bc/gov/splunknotificationservice/Service/WebHookServiceImpl.java, src/main/resources/application.properties
=> Moved properties to env

src/main/java/ca/bc/gov/splunknotificationservice/Configuration/SplunkProperites.java, src/main/java/ca/bc/gov/splunknotificationservice/Service/WebHookServiceImpl.java, src/main/resources/application.properties
=> Enable and disable webhook posts

.env, .gitignore, pom.xml, src/main/java/ca/bc/gov/splunknotificationservice/Model/TeamsAction.java, src/main/java/ca/bc/gov/splunknotificationservice/Model/TeamsCard.java, src/main/java/ca/bc/gov/splunknotificationservice/Model/TeamsFact.java, src/main/java/ca/bc/gov/splunknotificationservice/Model/TeamsInput.java, src/main/java/ca/bc/gov/splunknotificationservice/Model/TeamsPotentialActions.java, src/main/java/ca/bc/gov/splunknotificationservice/Model/TeamsSection.java, src/main/java/ca/bc/gov/splunknotificationservice/Service/WebHookServiceImpl.java, src/main/resources/application.properties
- basic teams card models
- simple map for teams cards
=> Initial addition of TeamsCard support

.github/workflow/maven-test-pr.yml
=> test baby test

src/main/java/ca/bc/gov/splunknotificationservice/configuration/SplunkProperites.java, src/main/java/ca/bc/gov/splunknotificationservice/controller/TeamsAlertController.java, src/main/java/ca/bc/gov/splunknotificationservice/service/TeamsWebHookService.java, src/main/java/ca/bc/gov/splunknotificationservice/service/TeamsWebHookServiceImpl.java, src/main/resources/application.properties
New teams endpoint with token and encodedUrl
=> New teams endpoint

src/main/java/ca/bc/gov/splunknotificationservice/service/WebHookServiceImpl.java
Added Message to Teams and RocketChat
Removed Link from Teams but left teamsFactLink for now in case we decide to use
=> Add message field to teams and rocketchat

src/main/java/ca/bc/gov/splunknotificationservice/service/ChannelServiceFactory.java, src/main/java/ca/bc/gov/splunknotificationservice/service/WebHookServiceImpl.java, src/main/java/ca/bc/gov/splunknotificationservice/splunk/models/SplunkResult.java, src/main/java/ca/bc/gov/splunknotificationservice/splunk/models/SplunkWebHookParams.java, src/main/java/ca/bc/gov/splunknotificationservice/splunk/models/SplunkWebHookUrls.java
Adds factory to allow for multiple urls for the same Chat app
=> Start factory implementation

src/main/java/com/nttdata/nttdatanotificationservice/teams/TeamsChannelService.java, src/main/java/com/nttdata/nttdatanotificationservice/teams/models/TeamsAction.java, src/main/java/com/nttdata/nttdatanotificationservice/teams/models/TeamsCard.java, src/main/java/com/nttdata/nttdatanotificationservice/teams/models/TeamsChoice.java, src/main/java/com/nttdata/nttdatanotificationservice/teams/models/TeamsFact.java, src/main/java/com/nttdata/nttdatanotificationservice/teams/models/TeamsInput.java, src/main/java/com/nttdata/nttdatanotificationservice/teams/models/TeamsPotentialActions.java, src/main/java/com/nttdata/nttdatanotificationservice/teams/models/TeamsSection.java, src/test/java/com/nttdata/nttdatanotificationservice/teams/TeamsChannelServiceTest.java
Fix #56
Refactored TeamsChannelService
=> Refactored TeamsChannelService

pom.xml
=> Added jacoco

src/main/resources/public/index.html, src/main/resources/public/index.js
- ensure urls are entered and are valid urls
close #45
=> Error checking and validation for inputs

.gitignore, package-lock.json, package.json, src/main/resources/public/index.js, src/main/resources/public/index.test.js, src/main/resources/public/testrunner.html
Frontend unit tests with Mocha ☕ and our own custom frontend test runner page to view the test results 💯 
https://github.com/akroon3r/splunk-notification-service/issues/88
=> Frontend Unit Tests!

src/main/java/com/nttdata/nttdatanotificationservice/rocket/RocketChannelService.java, src/main/java/com/nttdata/nttdatanotificationservice/splunk/models/SplunkResult.java, src/main/java/com/nttdata/nttdatanotificationservice/teams/TeamsChannelService.java, src/test/java/com/nttdata/nttdatanotificationservice/rocket/RocketChannelServiceTest.java, src/test/java/com/nttdata/nttdatanotificationservice/teams/TeamsChannelServiceTest.java
- add button in teams to dashboard if provided
- add link in RocketMessage to dashboard if provided
- add unit test for RocketChannelService
Resolves #83
=> Add Dashboard Button/Url

Dockerfile, README.md, src/main/resources/public/testrunner.html
=> README!!! No like actually, please read me!

README.md
=> PLEASE README!!

README.md
Update naming to `ntt-data` instead of `splunk`
=> Update readme naming

src/main/resources/public/index.js
Pull values from non submitted input fields as well to improve UX
(Don't jump in the lake just cause someone tells you to)
=> Fix input field UX

src/main/java/com/nttdata/nttdatanotificationservice/sources/splunk/models/SplunkAlert.java, src/test/java/com/nttdata/nttdatanotificationservice/service/WebHookServiceImplTest.java
=> Update variable names to match camelcase

src/main/resources/application.properties, src/main/resources/application.yml, src/main/resources/public/index.js
- fix object naming when generating encoded url list
- remove application.properties file
- move settings from application.properties into .yml file
=> Update: Fix url naming generation, refactor properties

.github/dependabot.yml
Where the POM at for dependabot?
=> Find POM file for dependabot

src/main/java/com/nttdata/nttdatanotificationservice/controller/SplunkNotificationController.java, src/test/java/com/nttdata/nttdatanotificationservice/controller/SplunkNotificationControlllerTest.java
- fix mapping from splunk body
- fixed tests for new mapping
=> Fix object mapping from splunk

.env.example, src/main/java/com/nttdata/nttdatanotificationservice/configuration/NotificationBody.java, src/main/java/com/nttdata/nttdatanotificationservice/controller/UpdateCardController.java, src/main/java/com/nttdata/nttdatanotificationservice/service/WebHookService.java, src/main/java/com/nttdata/nttdatanotificationservice/teams/TeamsChannelService.java, src/main/resources/application.yml
- move token list from properties to a coma-delimited list in an env var
- remove unused imports
=> Refactor: Move token list to env var

src/main/java/com/nttdata/nttdatanotificationservice/controller/NotificationController.java, src/main/java/com/nttdata/nttdatanotificationservice/service/WebHookServiceImpl.java, src/test/java/com/nttdata/nttdatanotificationservice/controller/NotificationControllerTest.java
- remove unused route info from the generic route
- added header info to post (required by RocketChat)
=> Fix: Posting to RocketChat

src/main/java/com/nttdata/nttdatanotificationservice/controller/NotificationController.java, src/test/Notification Env.postman_environment.json, src/test/Notification Service.postman_collection.json, src/test/java/com/nttdata/nttdatanotificationservice/controller/NotificationControllerTest.java, src/test/java/com/nttdata/nttdatanotificationservice/controller/SplunkNotificationControlllerTest.java, src/test/java/com/nttdata/nttdatanotificationservice/controller/UpdateCardControllerTest.java
- add postman collection
- add env for collection
- remove unused imports
References #44
=> Add: Postman collection & env
